/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_example_WRAP_H_
#define SWIG_example_WRAP_H_

struct SwigDirector_SwigCallbackImpl : public SwigCallbackImpl, public Swig::Director {

public:
    SwigDirector_SwigCallbackImpl();
    virtual ~SwigDirector_SwigCallbackImpl();
    virtual void call(ParamStruct const &arg0);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackcall);

private:
    SWIG_Callback0_t swig_callbackcall;
    void swig_init_callbacks();
};


#endif
